apiVersion: v1
kind: Service
metadata:
  name: opens
  namespace: default
spec:
  selector:
    app: opens
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opens
  template:
    metadata:
      labels:
        app: opens
    spec:
      containers:
        - name: opens
          image: varunramg/opens:latest
          ports:
            - containerPort: 8080
          env:
            - name: OPENS_PORT
              value: 8081
            - name: OPENS_POP
              value: 8081
            - name: OPENS_SB
              value: 8081
            - name: OPENX_URL
              value: 8081
            - name: OPENX_INSECURE
              value: false
            - name: OPENX_CODE
              valueFrom:
                secretKeyRef:
                  name: openx-code
                  key: OPENX_CODE
          imagePullPolicy: Always